In [1]:
import numpy as np

In [2]:
MAS = np.array([
    [-100,-38,145,145,145,145],
    [-68,-86,98,280,280,280],
    [-116,-133,50,230,410,410],
    [-166,-118,1,360,510,700]
],dtype=object)
X_i=np.array([20,30,40,50],dtype=object)
S_j=np.array([0,10,20,30,40,50],dtype=object)

# Критерій Уолда (обережного спостереження)

In [3]:
print("Масив \n",MAS)
X_i_bad = np.amin(MAS,axis=1)
print("Найгірші X_i \n",X_i_bad)
Result = np.amax(X_i_bad)
print("Обране значення  \n",Result)

module = np.absolute(MAS-Result)
sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print(f"i = {i},X_i = {X_i[i]}, j = {j}, S_j = {S_j[j]} Значення",MAS[j][i])

Масив 
 [[-100 -38 145 145 145 145]
 [-68 -86 98 280 280 280]
 [-116 -133 50 230 410 410]
 [-166 -118 1 360 510 700]]
Найгірші X_i 
 [-100 -86 -133 -166]
Обране значення  
 -86
i = 1,X_i = 30, j = 1, S_j = 10 Значення -86


Отже, якщо побудуємо гостиницю з 30-ма кімнатами і будуть використовуватися лище з 10 зних, то ми втратимо лище 86 грошових одиниць.

# Критерій Лапласа 

In [4]:
print("Масив \n",MAS)
L = np.sum(MAS, axis = 1)/len(MAS[0])
Result = np.amax(L)
print("L = ", L, "\n max_L = ",Result)
module = np.absolute(MAS-Result)

sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print(f"i = {i},X_i = {X_i[i]}, j = {j}, S_j = {S_j[j]} Значення",MAS[j][i])

Масив 
 [[-100 -38 145 145 145 145]
 [-68 -86 98 280 280 280]
 [-116 -133 50 230 410 410]
 [-166 -118 1 360 510 700]]
L =  [73.66666666666667 130.66666666666666 141.83333333333334 214.5] 
 max_L =  214.5
i = 3,X_i = 50, j = 2, S_j = 20 Значення 230


Отже, якщо побудуємо гостиницю з 50-ма кімнатами і будуть використовуватися лище з 20 зних, то наш прибуток буде становити 230 грошових одиниць.

# Критерій Гурвиця

In [5]:
l = 0.6
max_i = np.amax(MAS, axis = 1)
min_j = np.amin(MAS, axis = 1)
mid = (1-l)*min_j+l*max_i
max_mid = np.amax(mid)
print("Масив \n",MAS,"\n Отриманий результат \n",max_mid,"\n")

module = np.absolute(MAS-max_mid)
sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print(f"i = {i},X_i = {X_i[i]}, j = {j}, S_j = {S_j[j]} Значення",MAS[j][i])

Масив 
 [[-100 -38 145 145 145 145]
 [-68 -86 98 280 280 280]
 [-116 -133 50 230 410 410]
 [-166 -118 1 360 510 700]] 
 Отриманий результат 
 353.6 

i = 3,X_i = 50, j = 3, S_j = 30 Значення 360


Отже, якщо побудуємо гостиницю з 50-ма кімнатами і будуть використовуватися лище з 30 зних, то наш прибуток буде становити 360 грошових одиниць.

# Критерій Севіджа

print("Масив \n",MAS)
max_i = np.amax(MAS,axis=0)
print("Найкращий результат кожної графи \n",max_i)
r = np.zeros(MAS.shape)
for j in range (len(MAS)):
    for i in range (len(MAS[0])):
        r[j][i] = max_i[i]-MAS[j][i]
print("Відхилення відкращого результату кожної окремої графи\n",r)
max_j = np.amax(r,axis=1)
print("Матриця жалю\n",max_j)
res = np.min(max_j,axis=0)
print("Обираємо рішення, за якого максимальний жаль буде меншим, ніж за інших рішень\n",res)
j,i = np.where(r == res); i = i[0];j=j[0]
f_res = MAS[j][i]
print(f"i = {i},X_i = {X_i[i]}, j = {j}, S_j = {S_j[j]} Значення",MAS[j][i])

Отже, якщо побудуємо гостиницю з 40-ма кімнатами і будуть використовуватися лище з 30 зних, то наш прибуток буде становити 1 грошову одиницю.

# Висновки

1) Якщо побудуємо гостиницю з 30-ма кімнатами і будуть використовуватися лище з 10 зних, то ми втратимо лище 86 грошових одиниць. (Не будуємо)


2) Якщо побудуємо гостиницю з 50-ма кімнатами і будуть використовуватися лище з 20 зних, то наш прибуток буде становити 230 грошових одиниць.

 3) Якщо побудуємо гостиницю з 50-ма кімнатами і будуть використовуватися лище з 30 зних, то наш прибуток буде становити 360 грошових одиниць.

4) Якщо побудуємо гостиницю з 40-ма кімнатами і будуть використовуватися лище з 30 зних, то наш прибуток буде становити 1 грошову одиницю.

Я би обрав варіант, де будуємо 50 кімнат, бо можна побачити, що виграш може окупити програші на перших етапах (розвиток готелю, коли людей мало). 

30, 40 --- варіанти, де на перший погляд все більш безпечно. Але прибуток буде обиежений як і розвиток готелю. І можна побачити, що скоріше за все  довгий час гостиниця не зможе окупитися. 20 --- не рекомендую будувати, бо шанс програти дуже великий і потрібно, щоб гостиниця була заповнена на усі 20 кімнат. 30 --- для початківця, якщо ресурсів на розвитку готелю немає + для стабільного доходу.  40 --- якщо людина готова більше вкластися у проект і тут вже виграш набагато смачніший. Якщо людина готова масштабуватися і може слідкувати за тим, щоб 30-40 кімнат використовувалося (чи володіє людина репутацією, грошима та іншим для забезпечення такого стану).

50 кімнат потребують багато ресурсів для будування. Але, якщо вдається заповнити 30 кімнат, то ми вже маємо чудовий прибуток. І не потрібно слідкувати за тим, щоб у нас бв постіний відтік і притік клієнтів. А виграш при від 40-50 заповнених кімнат надзвичайний і дозволить відкрити інші готелі.

Мені сподобався результат 3-го критерію. Я у своїх розумах також спирався на цю цифру. Тим паче я можу налаштувати кофіцієнт оптимізму (обрано 0.6).

In [6]:
print(f"MAS = \n{MAS}\n")
A = MAS[0:4,0:2]
print(f"A = \n{A}\n")
B = MAS[0:4,2:4]
print(f"B = \n{B}\n")
C = MAS[0:4,4:6]
print(f"C = \n{C}\n")
a = 0.2; b = 0.45;c = 0.35
print (f"a = {a}, b = {b}, c = {c} \n")
U = np.sum(A)*a/6+np.sum(B)*b/6+np.sum(C)*c/6
print(f"U = {U}")

module = np.absolute(MAS-U)
sup_min=np.amin(np.amin(module))
j,i = np.where(sup_min == module); i = i[0];j=j[0]

print(f"i = {i},X_i = {X_i[i]}, j = {j}, S_j = {S_j[j]} Значення",MAS[j][i])

MAS = 
[[-100 -38 145 145 145 145]
 [-68 -86 98 280 280 280]
 [-116 -133 50 230 410 410]
 [-166 -118 1 360 510 700]]

A = 
[[-100 -38]
 [-68 -86]
 [-116 -133]
 [-166 -118]]

B = 
[[145 145]
 [98 280]
 [50 230]
 [1 360]]

C = 
[[145 145]
 [280 280]
 [410 410]
 [510 700]]

a = 0.2, b = 0.45, c = 0.35 

U = 238.67499999999998
i = 3,X_i = 50, j = 2, S_j = 20 Значення 230


Виходячи з даних результатів при таких віогідностях і данних краще запропонувати 2-ий критерій.

Отже, будуємо готель на 50 кімнат :)